return {
 ["HaranoAjiGothic-Medium/B:mode=node;script=hani;language=dflt;#b#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium/BI:mode=node;script=hani;language=dflt;#bi#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium/I:mode=node;script=hani;language=dflt;#i#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;#717618"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;#717622"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;script=hani;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;script=hani;language=dflt;#717622"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;script=hani;language=dflt;-kern;jfm=ujis#796311"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiGothic-Medium:mode=node;script=hani;language=dflt;-kern;jfm=ujis#955571"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiGothic-Medium.otf", false },
 ["HaranoAjiMincho-Regular/B:mode=node;script=hani;language=dflt;#b#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular/BI:mode=node;script=hani;language=dflt;#bi#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular/I:mode=node;script=hani;language=dflt;#i#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;#717618"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;#717622"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;#717622"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#1146687"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#331796"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#464512"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#663593"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#796311"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
 ["HaranoAjiMincho-Regular:mode=node;script=hani;language=dflt;-kern;jfm=ujis#955571"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/haranoaji/HaranoAjiMincho-Regular.otf", false },
}